// generated by ../chj-ctest/bin/gendeps
#include "chj-ctest/test.h"

void __test_DD_chjM64lib_tod_int_to_BCD (struct TestStatistics *);
void __test_DD_chjM64lib_tod_t1 (struct TestStatistics *);
void __test_D_vm_mem_immediates (struct TestStatistics *);
void __test_D_vm_mem_IS_IN_FIX_RANGE (struct TestStatistics *);
void __test_D_vm_mem_scm_number_cmp (struct TestStatistics *);
void __test_D_vm_mem_scm_add (struct TestStatistics *);
void __test_D_vm_mem_t1 (struct TestStatistics *);
void __test_D_vmtest_basics (struct TestStatistics *);


void run_tests() {
    struct TestStatistics stats = { 0, 0 };
    run_test_(&stats, "int_to_BCD in \"../chj-64lib/tod.c\"", __test_DD_chjM64lib_tod_int_to_BCD);
    run_test_(&stats, "t1 in \"../chj-64lib/tod.c\"", __test_DD_chjM64lib_tod_t1);
    run_test_(&stats, "immediates in \"./vm_mem.c\"", __test_D_vm_mem_immediates);
    run_test_(&stats, "IS_IN_FIX_RANGE in \"./vm_mem.c\"", __test_D_vm_mem_IS_IN_FIX_RANGE);
    run_test_(&stats, "scm_number_cmp in \"./vm_mem.c\"", __test_D_vm_mem_scm_number_cmp);
    run_test_(&stats, "scm_add in \"./vm_mem.c\"", __test_D_vm_mem_scm_add);
    run_test_(&stats, "t1 in \"./vm_mem.c\"", __test_D_vm_mem_t1);
    run_test_(&stats, "basics in \"./vmtest.c\"", __test_D_vmtest_basics);
    print_teststatistics(&stats);
}
